
version: '3.8'
services:
    # The Go App
   
    # MongoDB
    mongo:
        image: 'mongo'
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always
    # Mongo Express Web-based MongoDB admin interface
    mongo_express:
        image: mongo-express
        container_name: mongo_express
        depends_on:
            - 'mongo'
        ports:
            - '8081:8081'
        restart: always
      
